cloudbase/openstack-hyperv-release-tests

windows/installnova.ps1
v2.0 is no longer supported in Mitaka, which can cause issues with the driver. This will lead to test failures.
=> Update admin auth url to v3 instead of v2.0

utils.sh
python-neutronclient's command "neutron agent-list" now displays the columns in a different order. This causes the check to fail and the build to be marked as failed.
=> Fixes neutron agent checks

utils.sh
Instead of checking the requested branch locally (which may not exist), check if the branch exists on the remote.
=> Check if branch exists on remote repo

utils.sh
When testing an older branch, the devstack setup might fail when setting up project databases. It will notice *.pyc db migration scripts, but no *.py files, raising an exception.
Cleanup all project *.pyc files on pull_all_git_repos.
=> Clean *.pyc files on pull

exclude-tests-default.txt, local.sh, run.sh
Adds interface_attach config option. This config option
refers to the ability to hotplug vNICs on running VMs.
This can only be done on Windows Hyper-V / Server 2016
with Generation 2 VMs.
Removes vNIC hotplug tests from exlude list.
Adds run_validation config option. With this config option,
the tests will also validate the operations (e.g.: it will
SSH into the guest).
=> Adds tempest config options

exclude-tests-default.txt
Tempest no longer has XML tests.
Remove other excluded tests.
=> Cleans up test exclude list

windows/installnova.ps1
By default, devstack uses "stackrabbit" as an RPC guest. Without this, compute nodes fail to authenticate.
=> Adds RPCBACKENDUSER installer argument

windows/installnova.ps1
There is no space between stackrabbit and RPCBACKENDPASSWORD, which results in a bad config being passed to the installer.
=> Adds missing whitespace

exclude-tests-default.txt
The current version of cirros does not have the ping6 command, causing the test_network_v6 tests to fail. Excluding them until the newest cirros is being used.
=> Adds test_network_v6 to exclude list

exclude-tests-default.txt
The AttachVolumeShelveTestJSON tests are failing due to the reported tempest bug [1].
The tests are count the partitions of  the guest VM by grep-ing vd* devices, but the guest has sd* devices.
[1] https://bugs.launchpad.net/tempest/+bug/1582730
=> Exclude failing tests due to tempest bug

windows/installnova.ps1
nova generates a lot of warnings because of the missing http prefix. Adding it will make the logs cleaner.
=> installer: Adds http prefix

run.sh
Some projects might have some local changes made, which will cause an error when trying to switch the branch
during stack. One example would be the global requirements project. [1]
[1] http://paste.openstack.org/show/566900/
=> Resets git repos before stacking

run.sh
Previous patch performed git reset and git clean on all folders in /opt/stack.
This patch ensures that the commands are only executed in folders that
have a .git folder, meaning that they are git repositories.
=> Cleans up only git repos

run.sh
Naming of stable branches contains "/" character.
This causes sed command to fail since "/" is a separator.
This also causes container creation to fail.
Fix consists of replacing the separator with something else.
Fix for container creation consists of replacing "/" character
in the container name with "-"
=> Fix NUC CI won't work for stable branches

windows/Utils.psm1
This commit does not add LiveMigration as a feature if the node to
which the MSI is being run, is inside a cluster. Cluster migration
network tags cannot be modified while being part of a cluster.
=> Skips LiveMigration feature inside a cluster

local.sh, run-all-tests.sh
96MB of ram were not enough to mount the device volume, so an
increase to 128MB fixed the problem. Default mtu, of 1500, with
the headers of vxlan was greater than what the network supported,
so it had to be decreased to 1450 inside the container. Elevated
rights were required to install the requirements.
=> Fixes tests

windows/Utils.psm1, windows/etc/nova.conf
Starting with Ocata, the placement API configuration is mandatory.
=> Adds placement API configuration options

local.sh
if branch != "stable/ocata" || branch != "master" is always true, no matter what value the branch has.
=> Fixes "always true" issue in local.conf

run.sh, utils.sh
Since Mitaka, neutron agent-list has a new column called
'availability_zone'. Passing the result to awk and testing for
the agent_type column this is located in position 5 for Kilo,
and for the upper versions on 6.
=> Fixes neutron agent-list on kilo

config.yaml
This commits changes the old HyperV2016_OVS_VXLAN_VHDX job to
HyperV2016_OVS_KILO_VXLAN_VHDX because the firewall_driver config
has to remain "neutron.plugins.hyperv.agent.security_groups_driver
.HyperVSecurityGroupsDriver" while on upper versions of devstack
this path no longer exists. Adds another job of
HyperV2016_OVS_VXLAN_VHDX which has the firewall_driver config
set to "openvswitch".
=> Adds job HyperV2016_OVS_VXLAN_VHDX

local.sh
We don't support this feature, and setting the "compute-feature-enabled.swap_volume" config option to False skips the test.
=> Excludes volume swap tests from tempest

run.sh, utils.sh
loop devices are allocated per container, and there are only 8
available loop devices. We need to clean them up, so we don't run
out of them, otherwise devstack will fail to setup.
=> Cleans up allocated loop devices

run.sh
Because the containers are being added to the known_hosts list, ssh-ing into a container having an IP which was previously allocated to another container will fail.
=> clears container from known hosts

run.sh
Having max_attempts higher than 0 could mask some possible issues by retrying the failing tests.
=> Reduce the max attempts to 0

local.sh
We shouldn't have to check the branch in order to delete a flavor. We can just || $true, and ignore the NotFound Errors.
=> local.sh: agnostically delete flavors

windows/SetupWinRMAccessSelfSigned.ps1
The curernt version of Win32 OpenSSL doesn't exist anymore, and it needs to be updated.
=> Updates OpenSSL installer

utils.sh
When evaluating an expression / cmd, backslashes are interpreted, which can be an undesired effect.
For example, executing:
exec_with_retry 2 1 get_win_config_files HOST C:\OpenStack\cloudbase\nova\etc LOCAL_PATH
The above path becomes: C:OpenStackcloudbasenovaetc, which is an invalid path.
=> Escapes backslashes on exec_with_retry
